# Generated by Django 4.1.1 on 2022-09-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11)),
                ('poll_id', models.CharField(max_length=15)),
                ('voted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=30)),
                ('valid_voters_card', models.BooleanField(default='False')),
                ('residential_status', models.BooleanField(default='True')),
                ('resident_state_id', models.IntegerField()),
                ('resident_lga_id', models.IntegerField()),
            ],
        ),
    ]
