# Generated by Django 4.1.1 on 2022-09-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='mac_address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='voter',
            name='resident_lga_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='resident_state_id',
            field=models.IntegerField(blank=True),
        ),
    ]
