# Generated by Django 4.1.1 on 2022-09-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_voter_last_name_alter_voter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
