# Generated by Django 4.1.1 on 2022-11-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_party_logo'),
        ('voters', '0002_remove_vote_candidate_vote_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.party'),
        ),
    ]
