# Generated by Django 4.1.1 on 2022-11-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_alter_vote_party'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
