# Generated by Django 4.1.1 on 2022-10-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_states_name'),
        ('voters', '0003_rename_last_name_voter_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='resident_lga_id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='resident_state_id',
        ),
        migrations.AddField(
            model_name='voter',
            name='resident_lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.lga'),
        ),
        migrations.AddField(
            model_name='voter',
            name='resident_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.states'),
        ),
    ]
