# Generated by Django 4.1.1 on 2022-10-28 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_remove_voter_ip_address_remove_voter_mac_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_ref', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='last_name',
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voters.voter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='age_range',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='employment_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='marital_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='state_of_origin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='device_id',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='voters.device'),
            preserve_default=False,
        ),
    ]
