# Generated by Django 4.1.1 on 2022-09-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senatorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('senatorial_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.senatorial')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.states')),
            ],
        ),
    ]
