# Generated by Django 4.1.1 on 2022-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.IntegerField(),
        ),
    ]
