# Generated by Django 4.1.1 on 2022-09-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_states_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='senatorial',
            name='state_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='utilities.states'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lga',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='senatorial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
