# Generated by Django 4.1.1 on 2023-01-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_constituency_alter_candidate_senatorial_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='state_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilities.state'),
            preserve_default=False,
        ),
    ]
