# Generated by Django 4.1.1 on 2022-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_subscriber_candidate_party_alter_candidate_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_picture',
            field=models.ImageField(default='Account-user.png', upload_to='candidate_pics'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='main_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
