# Generated by Django 4.1.1 on 2022-11-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_poll_party'),
        ('utilities', '0003_candidate_candidate_picture_candidate_main_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_party', to='utilities.party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_poll', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_state', to='utilities.state'),
        ),
    ]
