# Generated by Django 4.1.1 on 2022-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_senatorial_state_id_alter_lga_id_alter_senatorial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
