# Generated by Django 4.1.1 on 2023-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_constituency_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='abbr',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
