# Generated by Django 4.1.1 on 2023-01-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_alter_candidate_constituency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='constituency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.constituency'),
        ),
    ]
