# Generated by Django 4.1.1 on 2022-11-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_remove_poll_is_active'),
        ('utilities', '0005_alter_candidate_party_alter_candidate_poll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='poll_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pollCategory_candidate', to='poll.pollcategory'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='senatorial_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_candidate', to='utilities.senatorial'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='main_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_candidate', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_candidate', to='utilities.state'),
        ),
    ]
