# Generated by Django 4.1.1 on 2023-01-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_lga_constituency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='constituency_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilities.constituency'),
        ),
    ]
