# Generated by Django 4.1.1 on 2022-11-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_candidate_poll_category_candidate_senatorial_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_candidate', to='utilities.party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='senatorial_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_candidate', to='utilities.senatorial'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_candidate', to='utilities.state'),
        ),
    ]
