# Generated by Django 4.1.1 on 2023-01-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_alter_lga_constituency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
