# Generated by Django 4.1.1 on 2022-11-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_contact_remove_subscriber_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='logo',
            field=models.ImageField(default='Account-user.png', upload_to='party_pictures'),
        ),
    ]
