# Generated by Django 4.1.1 on 2023-01-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_alter_party_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.CharField(max_length=100),
        ),
    ]
