# Generated by Django 4.1.1 on 2023-01-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_alter_party_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
