# Generated by Django 4.1.1 on 2023-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
