# Generated by Django 4.1.1 on 2023-01-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_alter_hit_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hit',
        ),
    ]
