# Generated by Django 4.1.1 on 2022-11-04 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('roleName', models.CharField(choices=[('ADMIN', 'ADMIN'), ('SUPERADMIN', 'SUPERADMIN')], max_length=11)),
            ],
        ),
    ]
