# Generated by Django 4.1.1 on 2022-11-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('poll_description', models.TextField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_date', models.DateTimeField(editable=False)),
                ('poll_state', models.IntegerField()),
                ('poll_senatorial_district', models.IntegerField()),
                ('poll_lga', models.IntegerField()),
                ('poll_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollcategory')),
            ],
        ),
    ]
