# Generated by Django 4.1.1 on 2022-09-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
        ('utilities', '0002_alter_states_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('poll_date', models.DateTimeField(auto_now=True)),
                ('poll_description', models.TextField(max_length=200)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll_Category',
            fields=[
                ('poll_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
                ('poll_lga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.lga')),
                ('poll_senatorial_district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.senatorial')),
                ('poll_state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.states')),
            ],
        ),
        migrations.CreateModel(
            name='Poll_Option',
            fields=[
                ('poll_option_id', models.IntegerField(primary_key=True, serialize=False)),
                ('option_title', models.CharField(max_length=50)),
                ('option_image', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('poll_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll_category')),
            ],
        ),
        migrations.CreateModel(
            name='Poll_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll_option')),
                ('poll_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll_category')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voter')),
            ],
        ),
    ]
