# Generated by Django 4.1.1 on 2022-10-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_rename_last_name_voter_last_name'),
        ('utilities', '0004_alter_states_name'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('poll_description', models.TextField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=50)),
                ('option_image', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('poll_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='poll.pollcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll_option',
            name='poll_question_id',
        ),
        migrations.RemoveField(
            model_name='poll_result',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='poll_result',
            name='poll_option',
        ),
        migrations.RemoveField(
            model_name='poll_result',
            name='poll_question_id',
        ),
        migrations.RemoveField(
            model_name='poll_result',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_description',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_id',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_lga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.lga'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_senatorial_district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.senatorial'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utilities.states'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.DeleteModel(
            name='Poll_Category',
        ),
        migrations.DeleteModel(
            name='Poll_Option',
        ),
        migrations.DeleteModel(
            name='Poll_Result',
        ),
        migrations.AddField(
            model_name='pollresult',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AddField(
            model_name='pollresult',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.polloption'),
        ),
        migrations.AddField(
            model_name='pollresult',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.voter'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.pollcategory'),
            preserve_default=False,
        ),
    ]
