# Generated by Django 4.1.1 on 2022-12-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
        ('poll', '0001_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_votes', to='utilities.party'),
        ),
        migrations.AddField(
            model_name='votes',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='poll.poll'),
        ),
        migrations.AddField(
            model_name='votes',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_votes', to='voters.voter'),
        ),
        migrations.AddField(
            model_name='votecount',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_votes_count', to='utilities.party'),
        ),
        migrations.AddField(
            model_name='votecount',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes_count', to='poll.poll'),
        ),
        migrations.AddField(
            model_name='poll',
            name='party',
            field=models.ManyToManyField(related_name='poll_parties', to='utilities.party'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.pollcategory'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_senatorial_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_senatorial_district', to='utilities.senatorial'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_state', to='utilities.state'),
        ),
    ]
