# Generated by Django 4.1.1 on 2022-10-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_states_name'),
        ('poll', '0002_pollcategory_polloption_pollresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.lga'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_senatorial_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.senatorial'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.states'),
        ),
    ]
