# Generated by Django 4.1.1 on 2022-12-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_survey', to='poll.poll')),
                ('surveyCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_category', to='poll.surveycategory')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_survey', to='voters.voter')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
