# Generated by Django 4.1.1 on 2022-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_poll_enddate_poll_poll_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
