# Generated by Django 4.1.1 on 2022-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_candidate_candidate_picture_candidate_main_candidate'),
        ('poll', '0003_poll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='party',
            field=models.ManyToManyField(to='utilities.party'),
        ),
    ]
