# Generated by Django 4.1.1 on 2022-12-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_surveycategory_surveyresponse_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
