# Generated by Django 4.1.1 on 2022-11-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_lga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_senatorial_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
