# Generated by Django 4.1.1 on 2023-01-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_surveyresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycategory',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_survey_category', to='poll.poll'),
        ),
    ]
