# Generated by Django 4.1.1 on 2023-01-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_constituency_alter_candidate_senatorial_id_and_more'),
        ('poll', '0004_alter_surveyresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_constituency', to='utilities.constituency'),
        ),
    ]
