# Generated by Django 4.1.1 on 2022-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_poll_poll_lga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(default='Presidential Election', max_length=30),
        ),
    ]
