# Generated by Django 4.1.1 on 2023-01-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_surveycategory_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveycategory',
            name='poll',
        ),
    ]
