# Generated by Django 4.1.1 on 2023-01-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_poll_constituency'),
        ('poll', '0006_remove_surveycategory_poll'),
    ]

    operations = [
    ]
