# Generated by Django 4.1.1 on 2022-11-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_poll_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_lga',
        ),
    ]
