# Generated by Django 4.1.1 on 2022-11-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_is_active'),
        ('poll', '0007_alter_poll_party'),
    ]

    operations = [
    ]
