# Generated by Django 4.1.1 on 2022-11-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_merge_0002_poll_is_active_0007_alter_poll_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
    ]
