# Generated by Django 4.1.1 on 2022-11-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_remove_poll_poll_lga'),
        ('poll', '0009_remove_poll_is_active'),
    ]

    operations = [
    ]
