# Generated by Django 4.1.1 on 2022-11-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_remove_pollcategory_poll_description_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
