# Generated by Django 4.1.1 on 2022-11-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_votes_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='vote_count',
        ),
    ]
