# Generated by Django 4.1.1 on 2022-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_votecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecount',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
