# Generated by Django 4.1.1 on 2022-11-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_alter_votecount_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(default='Presidential Election', max_length=40),
        ),
    ]
