# Generated by Django 4.1.1 on 2022-12-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_party_logo'),
        ('poll', '0016_alter_poll_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_senatorial_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_senatorial_district', to='utilities.senatorial'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_state', to='utilities.state'),
        ),
    ]
